## Build instructions. ##
[build]
	base = "/"
	publish = "dist"
	command = "npm run compile"

## Headers. ##
[[headers]]
	for = "/*"
	[headers.values]
		Content-Security-Policy = "default-src 'self' https://*.paulshryock.dev"
		Cross-Origin-Embedder-Policy = "require-corp"
		Cross-Origin-Opener-Policy = "same-origin"
		Cross-Origin-Resource-Policy = "same-origin"
		Permissions-Policy = "accelerometer=(), ambient-light-sensor=(), autoplay=(), battery=(), camera=(), cross-origin-isolated=(), display-capture=(), document-domain=(), encrypted-media=(), execution-while-not-rendered=(), execution-while-out-of-viewport=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), navigation-override=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(), speaker-selection=(), conversion-measurement=(), focus-without-user-activation=(), hid=(), idle-detection=(), interest-cohort=(), serial=(), sync-script=(), trust-token-redemption=(), window-placement=(), vertical-scroll=()"
		Referrer-Policy = "strict-origin-when-cross-origin"
		X-Content-Type-Options = "nosniff"
		X-Frame-Options = "DENY"
		X-XSS-Protection = "1; mode=block"

## Redirects to default subdomain. ##
[[redirects]]
	from = "http://pshry.netlify.app"
	to = "https://www.paulshryock.dev/"
	status = 308
	force = true

[[redirects]]
	from = "http://pshry.netlify.app/*"
	to = "https://www.paulshryock.dev/:splat"
	status = 308
	force = true

[[redirects]]
	from = "https://pshry.netlify.app"
	to = "https://www.paulshryock.dev/"
	status = 308
	force = true

[[redirects]]
	from = "https://pshry.netlify.app/*"
	to = "https://www.paulshryock.dev/:splat"
	status = 308
	force = true

## Redirects to third-party URL's. ##
[[redirects]]
	from = "/behance"
	to = "https://www.behance.net/pshry"
	status = 308

[[redirects]]
	from = "/dribbble"
	to = "https://dribbble.com/pshry"
	status = 308

[[redirects]]
	from = "/github"
	to = "https://github.com/paulshryock"
	status = 308

[[redirects]]
	from = "/linkedin"
	to = "https://www.linkedin.com/in/paulshryock"
	status = 308

## Internal redirects. ##
[[redirects]]
	from = "/api/*"
	to = "/.netlify/functions/:splat"
	status = 200

## Server API routes. ##
[functions]
	directory = "src/routes/api"
