name: Deploy

on:
  push:
    tags:
      - v*

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3.3.0
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Compile source code
        run: npm run compile

      - name: Run acceptance tests
        run: npm run test:acceptance

      - name: Deploy preview
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npm run deploy -- --message=${GITHUB_REF##*/}
        if: ${{ contains( github.ref, 'alpha' ) || contains( github.ref, 'beta' ) || contains( github.ref, 'rc' ) }}

      - name: Deploy to production
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        run: npm run deploy -- --prod
        # todo: Check if is full release
        if: ${{ contains( github.ref, 'alpha' ) == false && contains( github.ref, 'beta' ) == false && contains( github.ref, 'rc' ) == false }}